### ISSUE TITLE
Uncaught TypeError: _ref.is is not a function and package no longer displays in 1.16.0 

### ISSUE THREAD

**Issue by burneyhoel** [postcasio/tree-view-open-files#49]
Not sure if this is an incompatibility issue with the update to 1.16.0 or if its an atom bug that will be worked out in a patch. Just wanted to let you know this package no longer displays and throws an uncaught typerror when toggling the tree view in 1.16.0.

Uncaught TypeError: _ref.is is not a function

Steps to reproduce: Toggle tree view off from the view menu.

1. ...
2. ...

**Atom**: 1.16.0 x64
**Electron**: 1.3.13
**OS**: Microsoft Windows 7 Professional 
**Thrown From**: [tree-view-open-files](https://github.com/postcasio/tree-view-open-files) package 0.3.0

### Stack Trace

Uncaught TypeError: _ref.is is not a function

```
At /C:/Users/user/.atom/packages/tree-view-open-files/lib/tree-view-open-files.coffee:29

TypeError: _ref.is is not a function
    at /packages/tree-view-open-files/lib/tree-view-open-files.coffee:22:27)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/app.asar/src/command-registry.js:259:29)
    at CommandRegistry.handleCommandEvent (/app.asar/src/command-registry.js:3:59)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/app.asar/src/command-registry.js:160:19)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchApplicationMenuCommand (/app.asar/src/atom-environment.js:1179:28)
    at EventEmitter.outerCallback (/app.asar/src/application-delegate.js:312:25)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:194:7)
```

### Commands

```
     -0:44.2.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-always.theme-zooce-syntax.theme-bliss-monokai-ui)
     -0:29.2.0 tree-view:toggle (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
```

### Non-Core Packages

```
apm-publish 0.3.2 
ask-stack 2.2.0 
atom-beautify 0.29.18 
atom-clock 0.1.6 
atom-keyboard-macros 0.9.2 
atom-runner 2.7.1 
atomatigit 1.5.5 
autocomplete-clang 0.10.1 
autocomplete-java 1.2.5 
autocomplete-json 5.4.0 
autocomplete-python 1.8.63 
blame 0.10.3 
bliss-monokai-ui 0.2.0 
build 0.67.0 
busy 0.7.0 
busy-signal 1.3.0 
chary-tree-view 0.2.3 
color-picker 2.2.5 
default-language 0.3.0 
export-html 3.1.0 
expose 0.14.0 
fancy-bracket-matcher 1.0.1 
file-icons 2.1.2 
find-list 0.3.0 
firewatch-syntax 1.1.1 
gaia-dark-syntax 2.0.0 
git-control 0.9.0 
git-diff-details 1.4.0 
git-history 3.3.0 
git-plus 7.4.0 
git-projects 1.17.0 
git-split-diff-hyperclick 0.3.12 
git-status 0.3.4 
git-time-machine 1.5.9 
goto 1.8.3 
hacking-the-kernel 1.6.2 
hacking-the-kernel-ui 1.6.2 
highlight-selected 0.13.1 
hyperclick 0.0.40 
indent-guide-improved 1.4.12 
ink 0.6.5 
intentions 1.1.2 
intentions-colorpicker 1.0.1 
javascript-snippets 1.2.1 
julia-client 0.5.12 
language-AHK 0.0.2 
language-arma-atom 2.9.0 
language-diff 0.7.0 
language-ini 1.19.0 
language-jbase 0.1.0 
language-julia 0.11.0 
language-lua 0.9.11 
language-pick-basic 0.5.2 
language-stellaris 0.0.5 
linter 2.1.2 
linter-gcc 0.7.1 
linter-jsonlint 1.3.0 
linter-lua 1.0.4 
linter-mixed-indent 1.1.0 
linter-pylama 0.8.16 
linter-python-pep8 0.2.0 
linter-ui-default 1.2.2 
merge-conflicts 1.4.4 
minimap 4.27.1 
minimap-bookmarks 0.4.2 
minimap-cursorline 0.2.0 
minimap-find-and-replace 4.5.2 
minimap-git-diff 4.3.1 
minimap-highlight-selected 4.6.1 
minimap-linter 2.0.0 
minimap-pigments 0.2.2 
minimap-selection 4.4.0 
minimap-split-diff 0.3.7 
navigate 0.1.17 
one-sharp-syntax 3.0.0 
open-git-modified-files 0.2.4 
open-recent 5.0.0 
package-list 0.1.2 
package-switch 0.5.0 
package-sync-plus 0.1.2 
pigments 0.39.1 
platformio-ide-terminal 2.5.0 
pretty-json 1.6.3 
project-manager 3.3.4 
python-tools 0.6.9 
script 3.14.1 
shell-it 0.2.1 
simple-drag-drop-text 0.3.4 
slack-chat 3.4.2 
sort-lines 0.14.0 
split-diff 1.3.0 
sync-settings 0.8.1 
tab-close 2.0.3 
terminal-plus 0.14.5 
todo-show 1.11.0 
tool-bar 1.1.0 
tool-bar-exec 0.0.3 
tree-view-git-branch 0.1.2 
tree-view-git-status 1.3.1 
tree-view-open-files 0.3.0 
vim-mode 0.66.0 
zooce-syntax 1.0.1 
```

**Comment by jackplug** [comment]
Ahh, my bad for not checking 'issues' first :( I will add my dump here instead to add more data

Steps to reproduce:

1. Update Atom to 1.17.0-beta0
2. Open atom and attempt to open tree view

**Atom**: 1.17.0-beta0 ia32
**Electron**: 1.3.14
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [tree-view-open-files](https://github.com/postcasio/tree-view-open-files) package 0.3.0


### Stack Trace

Uncaught TypeError: ref.is is not a function

```
At C:\Users\Stuart\.atom\packages\tree-view-open-files\lib\tree-view-open-files.coffee:22

TypeError: ref.is is not a function
    at /packages/tree-view-open-files/lib/tree-view-open-files.coffee:22:27)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (~/AppData/Local/atom/app-1.17.0-beta0/resources/app/src/command-registry.js:265:1)
    at ~/AppData/Local/atom/app-1.17.0-beta0/resources/app/src/command-registry.js:3:1
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (~/AppData/Local/atom/app-1.17.0-beta0/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:610:1)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (~/AppData/Local/atom/app-1.17.0-beta0/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:401:1)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (~/AppData/Local/atom/app-1.17.0-beta0/resources/app/src/window-event-handler.js:100:1)
    at HTMLDocument.<anonymous> (~/AppData/Local/atom/app-1.17.0-beta0/resources/app/src/window-event-handler.js:3:1)
```

### Commands

```
 22x -7:25.8.0 intentions:highlight (input.hidden-input)
     -7:24.6.0 core:save (input.hidden-input)
     -1:21.8.0 tree-view:toggle (input.hidden-input)
 20x -0:28.5.0 intentions:highlight (input.hidden-input)
     -0:27.4.0 tree-view:toggle (input.hidden-input)
```

### Non-Core Packages

```
atom-terminal 0.8.0 
autoclose-html 0.23.0 
autoprefixer 3.6.1 
busy-signal 1.3.0 
cssbeautify 1.3.0 
intentions 1.1.2 
language-twig 1.6.3 
linter 2.1.2 
linter-eslint 8.1.5 
linter-scss-lint 3.1.0 
linter-ui-default 1.2.2 
pigments 0.39.1 
project-manager 3.3.4 
sorter 1.1.0 
sync-settings 0.8.1 
tree-view-open-files 0.3.0 
```

**Comment by sgithens** [comment]
Same issue.

[Enter steps to reproduce:]

1.  Type Command+\ to hide the file tree view
or
1. Using the top menu 'View'->'Toggle Tree View'  gives the same error.

**Atom**: 1.16.0 x64
**Electron**: 1.3.13
**OS**: Mac OS X 10.11.6
**Thrown From**: [tree-view-open-files](https://github.com/postcasio/tree-view-open-files) package 0.3.0


### Stack Trace

Uncaught TypeError: _ref.is is not a function

```
At /Users/sgithens/.atom/packages/tree-view-open-files/lib/tree-view-open-files.coffee:29

TypeError: _ref.is is not a function
    at /packages/tree-view-open-files/lib/tree-view-open-files.coffee:29:59)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/app.asar/src/command-registry.js:259:29)
    at /app.asar/src/command-registry.js:3:59
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:599:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:390:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/app.asar/src/window-event-handler.js:106:36)
    at /app.asar/src/window-event-handler.js:3:59)
```

### Commands

```
     -6:09.8.0 tabs:split-right (div.title.icon.icon-markdown)
     -6:06.3.0 intentions:highlight (input.hidden-input)
     -6:06.0 symbols-tree-view:toggle (input.hidden-input)
  7x -1:11.2.0 tree-view:toggle (div.markdown-preview.native-key-bindings)
```

### Non-Core Packages

```
atom-beautify 0.29.23 
busy-signal 1.3.0 
intentions 1.1.2 
linter 2.1.4 
linter-ui-default 1.2.3 
markdown-themeable-pdf 1.2.0 
minimap 4.27.1 
monokai 0.22.0 
pdf-view 0.57.0 
print-atom 0.1.1 
sort-lines 0.14.0 
Sublime-Style-Column-Selection 1.7.4 
symbols-tree-view 0.14.0 
sync-settings 0.8.1 
tree-view-open-files 0.3.0 
unsaved-changes 0.1.0 
vim-mode-plus 0.91.0 
```

**Comment by anatoli26** [comment]
Same here, but seeing the problem just now (after atom 1.17.0 update). Any ETA for a fix?

**Comment by rafaelrp** [comment]
Same here, Atom v1.17.0

**Comment by 993162337** [comment]
Me too, Atom Mac v1.17.1

**Comment by woolson** [comment]
Me too, Atom Mac v1.17.1

**Comment by rafaelrp** [comment]
Hello, have any ETA for this fix?
Thanks!

**Comment by mikeerickson** [comment]
I have tracked down the problem here.  In my case, it is caused by the `tree-view-open-files` plugin.  If I remove this plugin, all works fine.

https://atom.io/packages/tree-view-open-files

**Comment by sgithens** [comment]
In the most recent version of Atom, it appears they've added a little half circle arrow button, which can now close the side menu, but using the keyboard shortcut, Command-\, still produces this issue.

**Comment by sergiu-gordienco** [comment]
**Solved:** https://github.com/sergiu-gordienco/tree-view-open-files

on atom is tree-view-open-files-updated

`apm install tree-view-open-files-updated`

**Comment by orengriffin** [comment]
started happening for me like @sgithens described in version 1.19.2

**Comment by davelnewton** [comment]
And in 1.20.+

**Comment by juanluisbaptiste** [comment]
And on 1.21.1

**Comment by EEKimS** [comment]
Still an issue on 1.22.0

**Comment by wzs28150** [comment]
Same here, Atom v1.24.0

**Comment by jeromelachaud** [comment]
Same for me as well.
```
macOS 10.13.3
v1.26.0-beta0
```
