### ISSUE TITLE
Uncaught TypeError: ref.is is not a function

### ISSUE THREAD

**Issue by jackplug** [postcasio/tree-view-open-files#51]
[Enter steps to reproduce:]

1. Update Atom to 1.17.0-beta0
2. Open atom and attempt to open tree view

**Atom**: 1.17.0-beta0 ia32
**Electron**: 1.3.14
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [tree-view-open-files](https://github.com/postcasio/tree-view-open-files) package 0.3.0

### Stack Trace

Uncaught TypeError: ref.is is not a function

```
At C:\Users\Stuart\.atom\packages\tree-view-open-files\lib\tree-view-open-files.coffee:22

TypeError: ref.is is not a function
    at /packages/tree-view-open-files/lib/tree-view-open-files.coffee:22:27)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (~/AppData/Local/atom/app-1.17.0-beta0/resources/app/src/command-registry.js:265:1)
    at ~/AppData/Local/atom/app-1.17.0-beta0/resources/app/src/command-registry.js:3:1
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (~/AppData/Local/atom/app-1.17.0-beta0/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:610:1)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (~/AppData/Local/atom/app-1.17.0-beta0/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:401:1)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (~/AppData/Local/atom/app-1.17.0-beta0/resources/app/src/window-event-handler.js:100:1)
    at HTMLDocument.<anonymous> (~/AppData/Local/atom/app-1.17.0-beta0/resources/app/src/window-event-handler.js:3:1)
```

### Commands

```
 22x -7:25.8.0 intentions:highlight (input.hidden-input)
     -7:24.6.0 core:save (input.hidden-input)
     -1:21.8.0 tree-view:toggle (input.hidden-input)
 20x -0:28.5.0 intentions:highlight (input.hidden-input)
     -0:27.4.0 tree-view:toggle (input.hidden-input)
```

### Non-Core Packages

```
atom-terminal 0.8.0 
autoclose-html 0.23.0 
autoprefixer 3.6.1 
busy-signal 1.3.0 
cssbeautify 1.3.0 
intentions 1.1.2 
language-twig 1.6.3 
linter 2.1.2 
linter-eslint 8.1.5 
linter-scss-lint 3.1.0 
linter-ui-default 1.2.2 
pigments 0.39.1 
project-manager 3.3.4 
sorter 1.1.0 
sync-settings 0.8.1 
tree-view-open-files 0.3.0 
```

**Comment by jackplug** [comment]
Duplicate https://github.com/postcasio/tree-view-open-files/issues/49

**Comment by mikeerickson** [comment]
I have tracked down the problem here.  In my case, it is caused by the `tree-view-open-files` plugin.  If I remove this plugin, all works fine.

https://atom.io/packages/tree-view-open-files
