### ISSUE TITLE
Uncaught TypeError: ref.is is not a function

### ISSUE THREAD

**Issue by mittalyashu** [postcasio/tree-view-open-files#54]
```
C:\Users\YASHU\.atom\packages\tree-view-open-files\lib\tree-view-open-files.coffee:22

TypeError: ref.is is not a function
    at atom-workspace.<anonymous> (file:///C:/Users/YASHU/.atom/packages/tree-view-open-files/lib/tree-view-open-files.coffee:22:27)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\YASHU\AppData\Local\atom\app-1.18.0\resources\app\src\command-registry.js:265:35)
    at C:\Users\YASHU\AppData\Local\atom\app-1.18.0\resources\app\src\command-registry.js:3:65
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (C:\Users\YASHU\AppData\Local\atom\app-1.18.0\resources\app\node_modules\atom-keymap\lib\keymap-manager.js:610:22)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (C:\Users\YASHU\AppData\Local\atom\app-1.18.0\resources\app\node_modules\atom-keymap\lib\keymap-manager.js:401:28)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (C:\Users\YASHU\AppData\Local\atom\app-1.18.0\resources\app\src\window-event-handler.js:100:42)
    at HTMLDocument.<anonymous> (C:\Users\YASHU\AppData\Local\atom\app-1.18.0\resources\app\src\window-event-handler.js:3:65)
```

Here is the screenshot:
![image](https://user-images.githubusercontent.com/29014463/28658931-1d57ae88-72cb-11e7-8600-3d4edf54da15.png)

**Comment by sergiu-gordienco** [comment]
**Solved:** https://github.com/sergiu-gordienco/tree-view-open-files

on atom is tree-view-open-files-updated

supported by atom 1.18.0

`apm install tree-view-open-files-updated`

**Comment by hamstu** [comment]
@sergiu-gordienco Tried that one, still getting an error on latest Atom / macOS.

**Comment by mdeuerlein** [comment]
Still the same error here with Atom 1.19.3 for MacOS:

`TypeError: ref.is is not a function
    at HTMLElement.<anonymous> (/Users/mdeuerlein/.atom/packages/tree-view-open-files/lib/tree-view-open-files.coffee:22:27)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:265:35)
    at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:3:65)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:166:25)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchApplicationMenuCommand (/Applications/Atom.app/Contents/Resources/app/src/atom-environment.js:1338:34)
    at EventEmitter.outerCallback (/Applications/Atom.app/Contents/Resources/app/src/application-delegate.js:334:31)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:194:7)`

**Comment by coolgeng** [comment]
Same here, get the same error Atom 1.21.1 & MacOs Serria 10.12.6

**Comment by chrisvio** [comment]
Getting this error on Atom 1.22.1 & MacOS 10.13.1.

**Comment by dotjay** [comment]
Also getting this error on Atom 1.22.1 x64 & MacOS 10.13.1.

**Comment by evesala** [comment]
Seeing this on Atom 1.24.1 x64 on Windows 7.

**Comment by Mickamwamba** [comment]
Getting error on mac os Sierra 10.12.6

**Comment by jeromelachaud** [comment]
getting this error on High Sierra 10.13.3 with Atom 1.25.0
