### ISSUE TITLE
Uncaught TypeError: ref.is is not a function

### ISSUE THREAD

**Issue by cerberlink** [postcasio/tree-view-open-files#56]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.26.1 x64
**Electron**: 1.7.11
**OS**: Mac OS X 10.13.4
**Thrown From**: [tree-view-open-files](https://github.com/postcasio/tree-view-open-files) package 0.3.0

### Stack Trace

Uncaught TypeError: ref.is is not a function

```
At /Users/carlosguerrero/.atom/packages/tree-view-open-files/lib/tree-view-open-files.coffee:22

TypeError: ref.is is not a function
    at /packages/tree-view-open-files/lib/tree-view-open-files.coffee:22:27)
    at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:384:49)
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:621:22)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:412:28)
    at WindowEventHandler.handleDocumentKeyEvent (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:110:40)
```

### Commands

```
 18x -0:29.8.0 tree-view:toggle (input.hidden-input)
```

### Non-Core Packages

```
aesthetic-ui 4.0.0 
an-old-hope-syntax 1.0.4 
ask-stack 2.2.0 
atom-beautify 0.32.2 
atom-clock 0.1.16 
atom-eclipse-syntax 0.0.5 
atom-formatter-jsbeautify 1.1.2 
atom-jade 0.3.0 
atom-material-syntax 1.0.8 
atom-material-syntax-dark 1.0.0 
atom-material-syntax-light 0.4.6 
atom-material-ui 2.1.3 
atom-monokai 0.10.9 
atom-python-run 0.9.6 
atom-terminal 0.8.0 
atom-visual-studio-code-ui 1.3.4 
auto-update-packages 1.0.1 
autocomplete-clang 0.11.4 
autocomplete-java 1.2.7 
autocomplete-python 1.10.5 
autumn-highlighter-syntax 1.13.0 
brogrammer-ui 1.0.0 
busy-signal 1.4.3 
city-lights-syntax 1.1.8 
city-lights-ui 1.3.3 
clang-format 1.30.0 
emmet 2.4.3 
emmet-jsx-css-modules 1.0.0 
emmet-simplified 2.6.0 
emmet-snippets-compatibility 1.0.6 
es6-javascript 1.0.0 
file-icons 2.1.19 
formatter-clangformat 1.0.1 
gcc-make-run 0.2.12 
git-blame 1.6.0 
git-plus 7.10.2 
git-plus-plus 1.1.0 
git-plus-toolbar 1.0.1 
git-time-machine 1.5.9 
go-plus 5.8.3 
gpp-compiler 3.0.7 
gruvbox-plus-syntax 1.3.1 
hey-pane 1.1.0 
highlight-selected 0.13.1 
Hydrogen 2.4.1 
ide-cpp 0.0.3 
ide-java 0.8.3 
ide-python 0.9.2 
intentions 1.1.5 
isotope-light-ui 2.3.0 
jackhammer-syntax 1.1.0 
java-generator 2.2.3 
java-importer 1.4.1 
language-cpp14 0.6.2 
language-liquid 0.6.0 
linter 2.2.0 
linter-clang 4.1.2 
linter-gcc 0.7.1 
linter-javac 1.9.4 
linter-python 3.1.2 
linter-sass-lint 1.8.3 
linter-tidy 2.3.1 
linter-ui-default 1.7.1 
material-ui 1.0.10 
minimap 4.29.8 
minimap-find-and-replace 4.5.2 
minimap-highlight-selected 4.6.1 
minimap-pigments 0.2.2 
monokai 0.24.0 
monokai-dark 1.5.0 
monokai-seti 0.9.0 
native-ui 0.26.1 
nord-atom-ui 0.11.0 
nucleus-dark-ui 0.12.3 
oceanic-next 1.0.0 
open-recent 5.0.0 
pigments 0.40.2 
platformio-ide-terminal 2.8.1 
project-manager 3.3.5 
python-debugger 0.2.0 
python-indent 1.1.5 
python-isort 0.0.7 
python-tools 0.6.9 
rbe-matrix-syntax 0.2.1 
script 3.17.3 
script-runner 2.2.2 
scroll-through-time 0.3.0 
seti-ui 1.10.0 
seti-ui-red 0.13.0 
slack-ui 0.8.0 
styri-syntax 0.2.0 
switch-header-source 0.29.0 
teletype 0.13.1 
terminal-plus 0.14.5 
tool-bar 1.1.7 
tree-view-open-files 0.3.0 
unity-ui 2.1.11 
vim-mode-plus 1.32.0 
Visual-Studio-2015-Dark-Theme 2.4.2 
visual-studio-dark-syntax 0.2.0 
yeti-ui 0.1.6 
zentabs 0.8.9 
```

**Comment by erikig** [comment]
Addressed in #57
