### ISSUE TITLE
Failed to load the tree-view-open-files package

### ISSUE THREAD

**Issue by petrones** [postcasio/tree-view-open-files#57]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.27.1 x64
**Electron**: 1.7.15
**OS**: Mac OS X 10.13.4
**Thrown From**: [tree-view-open-files](https://github.com/postcasio/tree-view-open-files) package 0.3.0

### Stack Trace

Failed to load the tree-view-open-files package

```
At Cannot find module 'atom-utils'

Error: Cannot find module 'atom-utils'
    at Module._resolveFilename (module.js:470:15)
    at Module._resolveFilename (/Applications/Atom.app/Contents/Resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app/src/module-cache.js:354:58)
    at Module.require (/app.asar/static/index.js:40:43)
    at require (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:66:33)
    at /packages/tree-view-open-files/lib/tree-view-open-files.coffee:1:21)
    at /packages/tree-view-open-files/lib/tree-view-open-files.coffee:1:1)
    at /packages/tree-view-open-files/lib/tree-view-open-files.coffee:1:1)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .coffee] (/Applications/Atom.app/Contents/Resources/app/src/compile-cache.js:240:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (internal/module.js:20:19)
    at customRequire (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:96:26)
    at Package.requireMainModule (/Applications/Atom.app/Contents/Resources/app/src/package.js:782:33)
    at measure (/Applications/Atom.app/Contents/Resources/app/src/package.js:143:22)
    at Package.measure (/Applications/Atom.app/Contents/Resources/app/src/package.js:88:25)
    at Package.load (/Applications/Atom.app/Contents/Resources/app/src/package.js:129:16)
    at PackageManager.loadAvailablePackage (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:618:16)
    at config.transact (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:531:20)
    at Config.transact (/Applications/Atom.app/Contents/Resources/app/src/config.js:819:20)
    at PackageManager.loadPackages (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:529:23)
    at loadStatePromise.loadState.then (/Applications/Atom.app/Contents/Resources/app/src/atom-environment.js:833:27)
    at <anonymous>
```

### Commands

```
```

### Non-Core Packages

```
block-select 1.0.0 
atom-material-syntax 1.0.8 
atom-material-syntax-light 0.4.6 
atom-material-ui 2.1.3 
tree-view-open-files 0.3.0 
```

**Comment by erikig** [comment]
In case anyone is running into this issue, I was able to get around this using the @takeru and @bloopletech forks.
https://github.com/takeru/tree-view-open-files

I uninstalled the default package the from my command prompt, used `apm` to install the updated package

```
#Uninstall the default package (preferably using apm)
$ apm uninstall tree-view-open-files

#Install the updated package from git
$ cd ~/.atom/packages/
$ git clone https://github.com/takeru/tree-view-open-files
$ cd tree-view-open-files

#Install javascript dependencies
$ apm install
```

If this gets some activity I might create an official atom package from these forks.

![screenshot 2018-10-13 06 14 21](https://user-images.githubusercontent.com/1406045/46904282-e0becf00-ceaf-11e8-9826-25122b320d9a.png)

**Comment by delanym** [comment]
@erikig that fixes the bug, but I don't see any list of files. Is there another package people are using?

**Comment by delanym** [comment]
Goto https://atom.io/packages/open-files
