### ISSUE TITLE
Uncaught TypeError: Cannot read property 'is' of null

### ISSUE THREAD

**Issue by despairblue** [postcasio/tree-view-open-files#9]
Uncaught TypeError: Cannot read property 'is' of null

**Atom Version**: 0.156.0
**System**: linux 3.14.26-1-lts
**Thrown From**: [tree-view-open-files](https://github.com/postcasio/tree-view-open-files) package, v0.1.9
### Steps To Reproduce
1. open an atom project with the tree view hidden
2. press `ctrl+\' on linux to open the tree view

btw: pressing `ctrl+0` opens the tree view w/o error and after that `ctr+\` works as well
### Stack Trace

```
At /home/despairblue/.atom/packages/tree-view-open-files/lib/tree-view-open-files.coffee:17

TypeError: Cannot read property 'is' of null
  at atom-workspace.<anonymous> (/home/despairblue/.atom/packages/tree-view-open-files/lib/tree-view-open-files.coffee:17:25)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app/src/command-registry.js:243:29)
  at /usr/share/atom/resources/app/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/usr/share/atom/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:549:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/usr/share/atom/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:391:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/usr/share/atom/resources/app/src/window-event-handler.js:167:20)

```

/cc @atom/core

**Comment by sergiu-gordienco** [comment]
@**Try this**, fixed for atom 1.18.0 https://github.com/sergiu-gordienco/tree-view-open-files

on atom is tree-view-open-files-updated

`apm install tree-view-open-files-updated`

https://atom.io/packages/tree-view-open-files-updated
